// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbbmvwrvkgxwkojhmadu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYm12d3J2a2d4d2tvamhtYWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDQzNjgsImV4cCI6MjA3NDYyMDM2OH0.q--NHJ2HdbqHLKq4Oun3-unQtZ3guE6kZA65523O8EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});